### ISSUE TITLE
How to generate token from refresh_token  grant type?

### ISSUE THREAD

**Issue by Dsburn** [Basit-Mahmood/spring-authorization-server-password-grant-type-support#12] opened 2022-07-21 11:18 UTC
Hi, I'm trying this request without luck. Anything I missed up? Tq

curl --request POST \
  --url http://localhost:9301/oauth2/token \
  --header 'Authorization: Basic cGFzc3dvcmQtY2xpZW50LWlkOnNlY3JldDM=' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --cookie JSESSIONID=0E4B8931FDB781C689579278F0E79A51 \
  --data token=eyJraWQiOiIzYzBiZTczYS1iNGEyLTQ2YjQtOGEzNC1iMTlhYzE5M2U0MWMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImF1ZCI6InBhc3N3b3JkLWNsaWVudC1pZCIsIm5iZiI6MTY1ODQwMjA4Nywic2NvcGUiOlsiQURNSU4iLCJVU0VSIl0sImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MzAxXC9vYXV0aDJcL3Rva2VuIiwiZXhwIjoxNjU4NDg4NDg3LCJpYXQiOjE2NTg0MDIwODcsInVzZXJJZCI6Mn0.cXGCtRNNTa-LJ9mNveQs8jho401s6XacgDS9wCk6WQ-tA14oOBNiBHodjDBzkJFINaY6If0BMa6Udz0WUoL2sTbY6vlXSFjBx-1N2iyq7ACNgpF_RAthFQbvMhInR2L8OOTRXW1KMp7VH1gYv2r4dwFX8pDjmJ7PFJshlnuf9yodY87HMEJ5GOt6Ovs7GCcPd7alFid8e7x2w-5EiobEvJyXU22uJw1O4o9uSdwoeWJwnxT-OoIlK3NnZuOrO6cH4WE7WZ0lXorDRxEHCtnR5SjnVRsb1twjhESLrLyEWumV_kwSDVfcYvoeL1s0TSi38GzRjdFYBY2NGJqTFZnKbw \
  --data grant_type=refresh_token

Response :
 {
	"error_description": "OAuth 2.0 Parameter: refresh_token",
	"error": "invalid_request",
	"error_uri": "https://datatracker.ietf.org/doc/html/rfc6749#section-5.2"
}

**Comment by Basit-Mahmood** [comment] 2022-07-26 05:35
Hi, 

No need to send Authorization Basic. Send grant_type = refresh_token and refresh_token = [Your access token]. Optionally you can send scope = scope1 scope2 scope3 i.e., with space separated values.

Thanks & Regards
Basit Mahmood Ahmed

**Comment by welsh** [comment] 2022-10-31 22:44
@Basit-Mahmood , I did run into from downloading your example that if you change the `PasswordOAuth2RegisteredClient` to use the `ClientAuthenticationMethod` of `CLIENT_SECRET_BASIC` instead of `CLIENT_SECRET_POST` you can perform the following to get your access + refresh token:

```
curl --location --request POST 'http://localhost:9000/springauthserver/oauth2/token' \
--header 'Authorization: Basic cGFzc3dvcmQtY2xpZW50LWlkOnNlY3JldDM=' \
--form 'username="user1"' \
--form 'password="password"' \
--form 'grant_type="password"'
```

However, if you take the returned `refresh_token` value and pass it back to be refreshed:

```
curl --location --request POST 'http://localhost:9000/springauthserver/oauth2/token' \
--header 'Authorization: Basic cGFzc3dvcmQtY2xpZW50LWlkOnNlY3JldDM=' \
--form 'refresh_token="rALPmx7ouUhbxvEM1l10X0RRZ9Uf9vyxZfq_GDTkAW_Tsr_mN5Sbj-91itL-JW61uqKbONgkFR5dfqzidTV-BK41d_iTCgOQLOmJNMNBV0u5jdnQ6c8x3AxboHHjgil8"' \
--form 'grant_type="refresh_token"'
```
You instead get back:

`{"error":"invalid_grant"`

It appears from looking at the h2-console that the inserted record into the oauth2_authorization table has no values currently set:

```
ID                                      REGISTERED_CLIENT_ID      PRINCIPAL_NAME      AUTHORIZATION_GRANT_TYPE      ACCESS_TOKEN_ISSUED_AT        ACCESS_TOKEN_EXPIRES_AT       ACCESS_TOKEN_TYPE     REFRESH_TOKEN_VALUE     REFRESH_TOKEN_ISSUED_AT     REFRESH_TOKEN_EXPIRES_AT    REFRESH_TOKEN_METADATA  
08a9f199-c896-454d-ab46-8cf2364505b3    3                         user1               password                      2022-10-31 16:24:08.08645     2022-11-01 16:24:08.08645     Bearer                null                    null                        null                        null
e814fa82-ff20-466a-8e45-f00b03290d77    3                         user1               password                      2022-10-31 16:28:18.398117    2022-11-01 16:28:18.398117    Bearer                null                    null                        null                        null
fc7dee6e-bad9-4bba-b9b0-f2e35e44c0a2    3                         user1               password                      2022-10-31 16:34:22.101825    2022-11-01 16:34:22.101825    Bearer                null                    null                        null                        null
4b101592-2cf5-4556-ad37-50c58ab1226d    3                         user1               password                      2022-10-31 16:36:24.046945    2022-11-01 16:36:24.046945    Bearer                null                    null                        null                        null
```
So it is unable to perform the refresh, have you encountered this before?

**Comment by welsh** [comment] 2022-11-01 14:57
Ah, determined the issue was within `OAuth2ResourceOwnerPasswordAuthenticationProvider` where the `OAuth2Authorization.Builder authorizationBuilder` was not including the refresh token if the `REFRESH_TOKEN` grant was present.

Resolved by modifying it so that before building the `OAuth2Authorization` we set include the `refreshToken` if its present:
```
if (refreshToken != null) {
    authorizationBuilder.refreshToken(refreshToken);
}

OAuth2Authorization authorization = authorizationBuilder.build();
```

**Comment by ldw4033** [comment] 2022-12-24 05:19
I also encountered the problem that the token cannot be refreshed using the `authorization code` mode
```
SELECT * FROM OAUTH2_AUTHORIZATION 


ID | REGISTERED_CLIENT_ID | PRINCIPAL_NAME | AUTHORIZATION_GRANT_TYPE  
-- | -- | -- | -- 
443b30fd-7173-450c-909f-97cb3ae4f498 | 2 | user1 | authorization_code

```

{"error":"invalid_client"}

**Comment by Basit-Mahmood** [comment] 2022-12-24 09:14
@ldw4033 can you tell me the reproduction steps ?

**Comment by ldw4033** [comment] 2022-12-24 11:38
1. Start two project modules
SpringAuthorizationServerApplication [devtools] :9000/
SpringResourceServerApplication:8090/

2. Use postman (Version 10.6.7) to simulate the request
You can see the video [](https://1drv.ms/v/s!ArlfhfV51Tdjj3qsbHSVuTE4VlSy?e=sEKvKv)

3. Click `send` to get the data

```
[
     "Message 1",
     "Message 2",
     "Message 3"
]
```
4. But click `Refresh` and an error will be reported

**Comment by ldw4033** [comment] 2022-12-27 05:15
@Basit-Mahmood hi ,I know the cause of the problem, the code of `ClientAuthenticationMethod` here refers to `CLIENT_SECRET_POST` and the bug of postman software is still `CLIENT_SECRET_BASIC`

**Comment by Waylon-Firework** [comment] 2022-12-28 17:44
> Ah, determined the issue was within `OAuth2ResourceOwnerPasswordAuthenticationProvider` where the `OAuth2Authorization.Builder authorizationBuilder` was not including the refresh token if the `REFRESH_TOKEN` grant was present.
> 
> Resolved by modifying it so that before building the `OAuth2Authorization` we set include the `refreshToken` if its present:
> 
> ```
> if (refreshToken != null) {
>     authorizationBuilder.refreshToken(refreshToken);
> }
> 
> OAuth2Authorization authorization = authorizationBuilder.build();
> ```

You save me.

**Comment by Basit-Mahmood** [comment] 2023-01-15 19:39
@welsh @ldw4033 
I am sure that in the previous version I was missing the line `authorizationBuilder.refreshToken(refreshToken);` as mentioned by @welsh in his comments. In this version it has been fixed. 

Regarding @ldw4033 comments. I checked. It seems if you use `ClientAuthenticationMethod.CLIENT_SECRET_POST` in AuthorizationServer for registered client. Then from the client it should also use CLIENT_SECRET_POST. Similarly if you use CLIENT_SECRET_BASIC in AuthorizationServer  for registered client. Then from the client it should also use CLIENT_SECRET_BASIC. Otherwise invalid client exception will be throw from the spring.

Here are the cases that I ran. Hopefully it will clear the flow that why there is exception. You can see that in **Case 1** and **Case 4** spring is throwing exception

**Case 1** 

	0) In SpringAuthorizationServer Project change the following properties in application.properties file 
		oauth2.access.token.time = 1
		oauth2.access.token.time.unit = minute

		oauth2.refresh.token.time = 4
		oauth2.refresh.token.time.unit = hour
		
	1) In SpringAuthorizationServer Project change the class PasswordOAuth2RegisteredClient to use clientAuthenticationMethod CLIENT_SECRET_BASIC
		RegisteredClient passwordRegisteredClient = registeredClientBuilder.clientAuthenticationMethods(set -> Set.of(ClientAuthenticationMethod.CLIENT_SECRET_BASIC))
		
	2) In SpringAuthorizationServerCient Project change the class PasswordOAuth2Client to use clientAuthenticationMethod CLIENT_SECRET_POST
		.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_POST)
		
	3) Run the SpringAuthorizationServer Project (Run SpringAuthorizationServerApplication. This is a main class)
	4) Run the SpringResourceServer Project (Run SpringResourceServerApplication. This is a main class)
	5) Run the SpringAuthorizationServerCient Project (Run SpringAuthorizationServerClientApplication. This is a main class)
	6) Open the URL http://127.0.0.1:8080/springauthserverclient
	7) Login with user1 and password
	8) Click on Password grant type
	9) ClientSecretPostAuthenticationConverter invokes		(Spring internal class)
	10) ClientSecretAuthenticationProvider invokes                    (Spring internal class)
	11) **_throwInvalidClient("authentication_method");_**
	
**Case 2:**

	0) In SpringAuthorizationServer Project change the following properties in application.properties file 
		oauth2.access.token.time = 1
		oauth2.access.token.time.unit = minute

		oauth2.refresh.token.time = 4
		oauth2.refresh.token.time.unit = hour

	1) In SpringAuthorizationServer Project change the class PasswordOAuth2RegisteredClient to use clientAuthenticationMethod CLIENT_SECRET_BASIC
		RegisteredClient passwordRegisteredClient = registeredClientBuilder.clientAuthenticationMethods(set -> Set.of(ClientAuthenticationMethod.CLIENT_SECRET_BASIC))
		
	2) In SpringAuthorizationServerCient Project change the class PasswordOAuth2Client to use clientAuthenticationMethod CLIENT_SECRET_BASIC
		.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
		
	3) Run the SpringAuthorizationServer Project (Run SpringAuthorizationServerApplication. This is a main class)
	4) Run the SpringResourceServer Project (Run SpringResourceServerApplication. This is a main class)
	5) Run the SpringAuthorizationServerCient Project (Run SpringAuthorizationServerClientApplication. This is a main class)
	6) Open the URL http://127.0.0.1:8080/springauthserverclient
	7) Login with user1 and password
	8) Click on Password grant type
	9) ClientSecretBasicAuthenticationConverter invokes						(Spring internal class)
	10) ClientSecretAuthenticationProvider invokes							(Spring internal class)
	11) Successfully run;
	12) OAuth2TokenEndpointFilter invokes (/oauth2/token)					(Spring internal class)
	13) OAuth2ResourceOwnerPasswordAuthenticationConverter invokes
	14) OAuth2ResourceOwnerPasswordAuthenticationProvider invokes
	15) Response sends back
	16) Check the Database. Refresh token successful issued.
	16) After 1 minute again click on Password grant type. The Access token has expired now. 1 minute has been passed
	17) ClientSecretBasicAuthenticationConverter invokes					        (Spring internal class)
	18) ClientSecretAuthenticationProvider invokes							(Spring internal class)
	19) Successfully run;
	20) OAuth2RefreshTokenAuthenticationConverter invokes					(Spring internal class)
	21) OAuth2RefreshTokenAuthenticationProvider invokes					(Spring internal class)
	22) Response sends back
	23) Check the Database. Refresh token successful issued.
	
**Case 3:**

	0) In SpringAuthorizationServer Project change the following properties in application.properties file 
		oauth2.access.token.time = 1
		oauth2.access.token.time.unit = minute

		oauth2.refresh.token.time = 4
		oauth2.refresh.token.time.unit = hour

	1) In SpringAuthorizationServer Project change the class PasswordOAuth2RegisteredClient to use both clientAuthenticationMethod CLIENT_SECRET_BASIC and CLIENT_SECRET_POST
		RegisteredClient passwordRegisteredClient = registeredClientBuilder.clientAuthenticationMethods(set -> Set.of(ClientAuthenticationMethod.CLIENT_SECRET_BASIC, ClientAuthenticationMethod.CLIENT_SECRET_POST))
		
	2) In SpringAuthorizationServerCient Project change the class PasswordOAuth2Client to use clientAuthenticationMethod CLIENT_SECRET_BASIC
		.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
		
	3) Run the SpringAuthorizationServer Project (Run SpringAuthorizationServerApplication. This is a main class)
	4) Run the SpringResourceServer Project (Run SpringResourceServerApplication. This is a main class)
	5) Run the SpringAuthorizationServerCient Project (Run SpringAuthorizationServerClientApplication. This is a main class)
	6) Open the URL http://127.0.0.1:8080/springauthserverclient
	7) Login with user1 and password
	8) Click on Password grant type
	9) ClientSecretBasicAuthenticationConverter invokes					(Spring internal class)
	10) ClientSecretAuthenticationProvider invokes						(Spring internal class)
	11) Successfully run;
	12) OAuth2TokenEndpointFilter invokes (/oauth2/token)				(Spring internal class)
	13) OAuth2ResourceOwnerPasswordAuthenticationConverter invokes
	14) OAuth2ResourceOwnerPasswordAuthenticationProvider invokes
	15) Response sends back
	16) Check the Database. Refresh token successful issued.
	16) After 1 minute again click on Password grant type. The Access token has expired now. 1 minute has been passed
	17) ClientSecretBasicAuthenticationConverter invokes				        (Spring internal class)
	18) ClientSecretAuthenticationProvider invokes						(Spring internal class)
	19) Successfully run;
	20) OAuth2RefreshTokenAuthenticationConverter invokes				(Spring internal class)
	21) OAuth2RefreshTokenAuthenticationProvider invokes				(Spring internal class)
	22) Response sends back
	23) Check the Database. Refresh token successful issued.
	
**Case 4:**

	0) In SpringAuthorizationServer Project change the following properties in application.properties file 
		oauth2.access.token.time = 1
		oauth2.access.token.time.unit = minute

		oauth2.refresh.token.time = 4
		oauth2.refresh.token.time.unit = hour

	1) In SpringAuthorizationServer Project change the class PasswordOAuth2RegisteredClient to use both clientAuthenticationMethod CLIENT_SECRET_BASIC and CLIENT_SECRET_POST
		RegisteredClient passwordRegisteredClient = registeredClientBuilder.clientAuthenticationMethods(set -> Set.of(ClientAuthenticationMethod.CLIENT_SECRET_BASIC, ClientAuthenticationMethod.CLIENT_SECRET_POST))
		
	2) In SpringAuthorizationServerCient Project change the class PasswordOAuth2Client to use clientAuthenticationMethod CLIENT_SECRET_POST
		.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_POST)
		
	3) Run the SpringAuthorizationServer Project (Run SpringAuthorizationServerApplication. This is a main class)
	4) Run the SpringResourceServer Project (Run SpringResourceServerApplication. This is a main class)
	5) Run the SpringAuthorizationServerCient Project (Run SpringAuthorizationServerClientApplication. This is a main class)
	6) Open the URL http://127.0.0.1:8080/springauthserverclient
	7) Login with user1 and password
	8) Click on Password grant type
	9) ClientSecretPostAuthenticationConverter invokes				(Spring internal class)
	10) ClientSecretAuthenticationProvider invokes					(Spring internal class)
	11) **_throwInvalidClient("authentication_method");_**
	
**Case 5:**

	0) In SpringAuthorizationServer Project change the following properties in application.properties file 
		oauth2.access.token.time = 1
		oauth2.access.token.time.unit = minute

		oauth2.refresh.token.time = 4
		oauth2.refresh.token.time.unit = hour

	1) In SpringAuthorizationServer Project change the class PasswordOAuth2RegisteredClient to use CLIENT_SECRET_POST
		RegisteredClient passwordRegisteredClient = registeredClientBuilder.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_POST)
		
	2) In SpringAuthorizationServerCient Project change the class PasswordOAuth2Client to use clientAuthenticationMethod CLIENT_SECRET_POST
		.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_POST)
		
	3) Run the SpringAuthorizationServer Project (Run SpringAuthorizationServerApplication. This is a main class)
	4) Run the SpringResourceServer Project (Run SpringResourceServerApplication. This is a main class)
	5) Run the SpringAuthorizationServerCient Project (Run SpringAuthorizationServerClientApplication. This is a main class)
	6) Open the URL http://127.0.0.1:8080/springauthserverclient
	7) Login with user1 and password
	8) Click on Password grant type
	9) ClientSecretPostAuthenticationConverter invokes					(Spring internal class)
	10) ClientSecretAuthenticationProvider invokes						(Spring internal class)
	11) Successfully run;
	12) OAuth2TokenEndpointFilter invokes (/oauth2/token)				(Spring internal class)
	13) OAuth2ResourceOwnerPasswordAuthenticationConverter invokes
	14) OAuth2ResourceOwnerPasswordAuthenticationProvider invokes
	15) Response sends back
	16) Check the Database. Refresh token successful issued.
	16) After 1 minute again click on Password grant type. The Access token has expired now. 1 minute has been passed
	17) ClientSecretPostAuthenticationConverter invokes					(Spring internal class)
	18) ClientSecretAuthenticationProvider invokes						(Spring internal class)
	19) Successfully run;
	20) OAuth2RefreshTokenAuthenticationConverter invokes				(Spring internal class)
	21) OAuth2RefreshTokenAuthenticationProvider invokes				(Spring internal class)
	22) Response sends back
	23) Check the Database. Refresh token successful issued.

Thanks & Regards
Basit Mahmood Ahmed

**Comment by Basit-Mahmood** [comment] 2023-05-05 11:24
No response since long time. Closing the issue.

**Closed by Basit-Mahmood** 2023-05-05 11:24 UTC

**Comment by Waylon-Firework** [comment] 2023-08-19 07:31
Hi @Basit-Mahmood . Do you mean this is not the answer?

https://github.com/Basit-Mahmood/spring-authorization-server-password-grant-type-support/issues/12#issuecomment-1298630964
