### ISSUE TITLE
memory authentication problem

### ISSUE THREAD

**Issue by SSDespair** [Basit-Mahmood/spring-authorization-server-password-grant-type-support#5] opened 2021-11-16 04:53 UTC
At the time of memory authentication access scope error address: JdbcOAuth2AuthorizationService. Java: in the code
![image](https://user-images.githubusercontent.com/26852131/141923090-1b636999-a1f0-4b57-8f1d-62f7d0f2240e.png)
After modifying directly using set, there is no problem. You can take a look at this problem when you have time
![image](https://user-images.githubusercontent.com/26852131/141922916-3ce4394a-b7e4-46a9-b632-53d70ed4a745.png)

**Comment by Basit-Mahmood** [comment] 2021-11-22 10:12
@SSDespair  Hi,
Thanks you for your issue. But I didn't get your question completely. Are you talking about InMemoryRegisteredClientRepository and InMemoryOAuth2AuthorizationService. I mean if you configure your application using InMemoryRegisteredClientRepository and InMemoryOAuth2AuthorizationService. Then you are facing this issue or can you mention steps to reproduce?  Thanks

**Comment by SSDespair** [comment] 2021-11-23 02:53
This problem recurs when the token is refreshed.Here is my code address[https://github.com/SSDespair/auth-server-demo](url)

**Comment by SSDespair** [comment] 2021-11-23 02:59
This method resolves the previous error, when the code is used with the resource service, in fact, there will be a problem, because there is no permission to access, Processing I can do now is in OAuth2ResourceOwnerPasswordAuthenticationProvider. Add this code in the class, if you have a better treatment method, want to update in your code
![image](https://user-images.githubusercontent.com/26852131/142964737-2c34291c-d373-435a-b60c-2b3e0e2e09bc.png)

**Comment by Basit-Mahmood** [comment] 2021-11-23 08:29
I am really sorry. But still didn't get you completely. First of all you are saying OAuth2AuthorizationConsent is solving your problem. Consent is for authorization_code grant type flow. Consent  is nothing to do with password grant type. 

Secondly if you can tell me what is the problem then I can try to solve it. Specially if it is something that is related to password grant type. Because all other stuff are provided by spring.

What I did.

1) I set the access token time to one minute. (SpringAuthorizationServer project. Just change the property oauth2.access.token.time.unit = M in src/main/resources/application.properties)
2) I ran all the applications. SpringAuthorizationServer, SpringResourceServer and SpringAuthorizationServerClient. (I have all these applications in eclipse)
3) I opened the url http://127.0.0.1:8080/springauthserverclient in the browser.
4) Login with already populated username user1 and password password.
5) I clicked on the Password link. 
6) OAuth2ResourceOwnerPasswordAuthenticationProvider code invoked. Because I put the debug point in this file. This file ran successfully.
6) The response came.
7) I waited for one minute. So token expire.
8) After two minutes I again click on the Password link. Refresh token code invoked. And the response again come.

Now in this flow there is no error. Can you tell me like the steps above. What steps do I follow so your error will show up ?

Also if there is some error in JdbcOAuth2AuthorizationService. Then I cannot do anything. This is provided by spring. If you want to customize it then you have to do it by yourself.

In-fact When I integrated it with Oracle then it was not working. Because the query that was written was not supported by oracle. You can read it here [https://github.com/spring-projects/spring-authorization-server/issues/428](url) . Bu then I customized it according to my need. Because this is what I had been told to do so . Thanks :)

**Comment by SSDespair** [comment] 2021-11-23 09:06
Thank you for your help,I use the OAuth2ResourceOwnerPasswordAuthenticationProvider you write code, the database is msyql, operation will appear in my code to refresh token error the following error

![image](https://user-images.githubusercontent.com/26852131/142994769-4bfae743-730d-4d3e-9629-7bec4b1f92d6.png)

Your process is no problem, just use JdbcOAuth2AuthorizationService will because this value problem, lead to errors.
![image](https://user-images.githubusercontent.com/26852131/142995849-cf273228-d6b9-47ac-8689-4bea04a85246.png)

**Comment by Basit-Mahmood** [comment] 2021-11-23 09:25
@SSDespair Hi,

First of all this error has nothing to do with the OAuth2ResourceOwnerPasswordAuthenticationProvider that I wrote :) Second when token generates then it saves in database. And OAuth2refreshTokenAuthenticationProvided calls `this.authorizationService.findByToken(..)`. Which in turns call `JdbcOAuth2AuthoricationService`. Which if result finds call `RowMapper<OAuth2Authorization>`. Whatever the implementation is. You can customize it too. 

Now if you look at the implementation of default `JdbcOAuth2AuthorizationService.OAuth2AuthorizationRowMapper`. Then in the constructor you will find something like 

    `public OAuth2AuthorizationRowMapper(RegisteredClientRepository registeredClientRepository) {
			......
			List<Module> securityModules = SecurityJackson2Modules.getModules(classLoader);
			this.objectMapper.registerModules(securityModules);
			this.objectMapper.registerModule(new OAuth2AuthorizationServerJackson2Module());
		}`

So it is registering modules in objectMapper. In you code. In the configuration you use something like 

    `CustomOAuth2AuthorizationRowMapper oAuth2AuthorizationRowMapper = new CustomOAuth2AuthorizationRowMapper(registeredClientRepository);
     authorizationService.setAuthorizationRowMapper(oAuth2AuthorizationRowMapper);`

can you just check it in your configuration with the default rowmapper. I mean no need to set the above lines. Just use the default jdbc service. And see if it works. 

Because it seems that your configuration is overriding default spring objectmapper registerModules. 

Thanks

**Comment by SSDespair** [comment] 2021-12-02 07:44
Thank you for your help, ObjectMapper I added the mapping of the corresponding class, no problem

**Comment by Basit-Mahmood** [comment] 2021-12-02 09:31
@SSDespair Did your problem solve ?

**Comment by SSDespair** [comment] 2021-12-02 09:34
Yeah, it worked out.
![image](https://user-images.githubusercontent.com/26852131/144395492-96c0c65b-e02a-441b-9b48-3bd64a55cc68.png)
Obtaining the Token normally

**Comment by Basit-Mahmood** [comment] 2021-12-02 09:38
Aha It is good to know . Now I am closing this issue. Thanks :)

**Closed by Basit-Mahmood** 2021-12-02 09:38 UTC
